services:
  api:
    image: resume-parser-api
    build: 
      context: ./resume-parser-core
      dockerfile: Dockerfile
    env_file:
      - ./resume-parser-core/.env
    ports:
      - "8000:8000"
    restart: always

  webapp:
    image: resume-parser-webapp
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    env_file:
      - ./webapp/.env
    ports:
      - "80:80"
    restart: always